CREATE TABLE IF NOT EXISTS users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar NOT NULL,
  birthday date
);

CREATE TABLE IF NOT EXISTS users_friends (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users (user_id),
  friend_id integer REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS film_ratings (
  rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre varchar
);

CREATE TABLE IF NOT EXISTS films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar,
  release_date date NOT NULL,
  duration integer NOT NULL,
  film_rating_id integer REFERENCES film_ratings (rating_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer REFERENCES films (film_id),
  genre_id integer REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS films_likes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer REFERENCES films (film_id),
  user_id integer REFERENCES users (user_id)
);
